package model;

public enum PacketType {
    AUTHENTICATION_REQ,
    AUTHENTICATION_ERROR,
    AUTHENTICATION_SUCCESS,
    BYE,
    INFO_REQ,
    INFO_RES,
    PLAYING_REQ,
    PLAYING_RES,
    WATCH_REQ,
    WATCH_RES,
    SCORE_TABLE_REQ,
    SCORE_TABLE_RES
}
